### ISSUE TITLE
just curious where did you find this?!

### ISSUE THREAD

**Issue by neozeed** [jduerstock/mstcpsdk#1]
and thanks for posting it!

It sure would have been useful 20 years ago!

**Comment by jduerstock** [comment]
I found it on a web site.  It was something like "programmers corner" or "programmers heaven".  I found a reference to "mstcpsdk.rar" somewhere and just kept digging until I found it.

**Comment by neozeed** [comment]
super cool thanks for the hints!

**Comment by jduerstock** [comment]
I'm going to close this unless you have any further questions.

Are you doing to do a write up on this any time soon?

Also, I'm a big fan of your blog/site.  I enjoy reading about a lot of things you've worked on and poked at.

**Comment by neozeed** [comment]
Oh I'm totally sorry I didnt' realise this was left as an open issue for you!!!

There is no good way it seems to talk to people on here?  Its like the worst social media platform ever! lol

Thanks, glad you enjoy the site!  I've had so many things not work lately but i've been trying to get more stuff out.  the whole dos4 thing has been so much unexpected excitement! ...  Thanks again and sorry about this!

**Comment by jduerstock** [comment]
It's fine, no harm done.  I was just curious.
